Capstone
Duretitibesso3/capstone-project pull request #1
Opened 2022-05-27 15:33 UTC by Duretitibesso3

- create new repository
- Build the home page and about page 
- Each of these pages have versions for 2 different screen sizes Mobile: up to 768px wide and Desktop: 768px or wider.
- The section "Featured speakers"  created dynamically in JavaScript.
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- Record video about the project

2022-05-27 17:57 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Duretitibesso3,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-27 17:57 UTC, omar-muhamad commented on README.md
> +
- [ ] Please edit `Acknowledgments` section by giving appropriation and credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).
and kindly don't forget to include the links like I did.

- [ ] After the `Acknowledgments` section please add a `license` section Like the Microverse README template to make your readme file more professional.

2022-05-27 17:57 UTC, omar-muhamad commented on about.html
> +          <h1><a href="index.html">AYC</a></h1>
- [ ] Please remove the `<h1>` tag that wraps the logo link for semantic reasons because this is not your page's main header.

2022-05-27 17:57 UTC, omar-muhamad commented on about.html
> +      <h2>African Youth Confrance 2022</h2>
- [ ] Please put this text inside a `<h1>` tag instead of the `<h2>` tag because this is the main header on the page.

2022-05-27 17:57 UTC, Omar-Muhamad commented on about.html
> +    </section>
- [ ] Please include all this code inside one `<section>` tag and make the page `<header>` outside this section for semantic reasons.

2022-05-27 17:57 UTC, Omar-Muhamad commented on about.html
> +            <h1 class="past-event-title">2020</h1>
- [ ] Please use `h2` or `h3` for this heading because you are only allowed to use one `<h1>` tag per page for semantic reasons.

2022-05-27 17:57 UTC, Omar-Muhamad commented on about.html
> +            <h1 class="past-event-title">2021</h1>
- [ ] Same here.

2022-05-27 17:57 UTC, Omar-Muhamad commented on about.html
> +</section>
- [ ] Please remove the partners section from your about page to match the given design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170754558-ed6e0c16-1843-493d-adbe-4e9cd4029ff0.png)  | ![image](https://user-images.githubusercontent.com/68796232/170754276-63ac96c2-bd5f-494a-8cd5-e308d7bc52ea.png) |

2022-05-27 17:57 UTC, Omar-Muhamad commented on index.html
> +  </section>
- [ ] Same here Please include all this code inside one `<section>` tag and make the page `<header>` outside this section for semantic reasons.

2022-05-27 17:57 UTC, Omar-Muhamad commented on index.html
> +        <h1><a href="#hello">AYC</a></h1>
- [ ] Please remove the `<h1>` tag that wraps the logo link for semantic reasons because this is not your page's main header.

2022-05-27 17:57 UTC, Omar-Muhamad commented on index.html
> +    <h2>African Youth Confrance 2022</h2>
- [ ] Please make the `African Youth Conference 2022` text the main `<h1>` tag and `Hello!African Youth` the `<h2>` tag

2022-05-27 17:57 UTC, Omar-Muhamad commented on styles.css
> +}
In the mobile view for the headline section please fix the following:

- [ ] Kindly make the hamburger button bigger and make its color darker to match the given design.
- [ ] Please decrease the margin between the two heading texts to match the design.
- [ ] Please increase the width of the text box below the main heading to match the given design, Kindly see the images below to have more understanding.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170760699-14114ac5-49ff-433d-a6fb-0468d5ed0249.png)  | ![image](https://user-images.githubusercontent.com/68796232/170760671-d46ee9aa-cb26-4465-b817-db8b11aea7cc.png)  |

2022-05-27 17:57 UTC, Omar-Muhamad commented on styles.css
> +  }
for the headline section in the desktop view please fix the following:

- [ ] Kindly add the correct margin-top and margin-left values for the whole headline section to match the given design.
- [ ] Please decrease the width of the main heading to match the given design.
- [ ] Please decrease the margin between the two `<h3>` heading to match the given design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170763039-ac0f129f-458b-48f7-926e-fb4ad9380fb1.png)  | ![image](https://user-images.githubusercontent.com/68796232/170763000-35919967-367c-4d36-8271-c48dccd819cb.png)  |

2022-05-27 17:57 UTC, Omar-Muhamad commented on styles.css
> +    width: 100%;
For the program section on the desktop view:

- [ ] Please add the correct padding-top, padding-left, and padding-right to the whole section.
- [ ] Please make the width of the program cards equal and decrease the gap between them like the given design
- [ ] please fix the styling of the link by removing the orange background and adding only the underline to it and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170764227-5cc9cc75-2b72-4fec-bb1d-b0810f4addac.png) | ![image](https://user-images.githubusercontent.com/68796232/170764208-95f4dea4-aec6-4f07-b550-f593b1582063.png)  |

2022-05-28 19:35 UTC, danielufeli approved these changes
Hi @Duretitibesso3 , 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-05-28 19:38 UTC, merged